spring:
  application:
    name: erp-stock
eureka:
  client:
    service-url:
      defaultZone: http://admin:1008@localhost:8761/eureka ,http://admin:1008@localhost:8762/eureka #注册到 eureka服务中心
server:
  port: 7001
